openapi: 3.0.0
info:
  title: LogicApp Trigger API
servers:
  - url: https://prod-00.northcentralus.logic.azure.com:443/workflows/63478b0f2d2c47b0a6fb4921b2da86bb/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=x-W7N0_jF61bvnA3hSFR1wjP5tTgSBQwXFih_o6twfM
paths:
  /:
    post:
      summary: Trigger a specific action in the Logic App
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  description: The action to be performed by the Logic App.
              required:
                - action
      responses:
        '200':
          description: Successfully triggered the Logic App.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logic App triggered successfully."
        '400':
          description: Bad request if the payload is incorrect.
        '500':
          description: Internal server error.
